import { mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { CLI_CAPABILITY_REGISTRY, type CliCapability } from "@clobber/shared";
import { buildCommandRegistry } from "../src/main.ts";
import type { Command } from "../src/commands.ts";
import { baseRole, managerRole, workerRole } from "@clobber/runtime";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "../../..");

const BANNER =
  `> **AUTOGENERATED — do not edit.** Regenerate with \`bun run docs:gen\`. ` +
  `Source: cli-capabilities.ts, commands/*, role manifests.`;

// Source metadata files tracked for the changelog. Commits touching only
// docs/ produce no changelog entry — only changes to these sources do.
const CHANGELOG_SOURCES = [
  "packages/shared/src/domain/cli-capabilities.ts",
  "packages/cli/src/main.ts",
  "packages/runtime/roles/base/manifest.ts",
  "packages/runtime/roles/manager/manifest.ts",
  "packages/runtime/roles/worker/manifest.ts",
] as const;

export async function generateDocs(outputDir: string): Promise<void> {
  for (const dir of ["cli", "permissions", "roles"]) {
    mkdirSync(join(outputDir, dir), { recursive: true });
  }

  const commands = [...buildCommandRegistry().list()].sort((a, b) =>
    a.name.localeCompare(b.name),
  );

  const capabilities = Object.values(CLI_CAPABILITY_REGISTRY)
    .filter((cap) => !cap.internal)
    .sort((a, b) => a.name.localeCompare(b.name));

  const changelog = buildChangelog();

  put(outputDir, "index.md", renderIndex());
  put(outputDir, "cli/index.md", renderCliIndex(commands));
  for (const cmd of commands) {
    put(outputDir, `cli/${cmd.name}.md`, renderCliVerb(cmd));
  }
  put(outputDir, "permissions/index.md", renderPermissions(capabilities));
  put(outputDir, "roles/index.md", renderRoles());
  put(outputDir, "CHANGELOG.md", renderChangelog(changelog));
}

function put(base: string, rel: string, content: string): void {
  writeFileSync(join(base, rel), content);
}

function renderIndex(): string {
  return (
    `${BANNER}\n\n` +
    `# Clobber Documentation\n\n` +
    `- [CLI reference](cli/index.md)\n` +
    `- [Permissions](permissions/index.md)\n` +
    `- [Roles](roles/index.md)\n` +
    `- [Changelog](CHANGELOG.md)\n`
  );
}

function renderCliIndex(commands: readonly Command[]): string {
  const rows = commands
    .map((c) => `| [\`${c.name}\`](${c.name}.md) | ${c.summary} |`)
    .join("\n");
  return (
    `${BANNER}\n\n` +
    `# CLI Reference\n\n` +
    `| Command | Summary |\n` +
    `| ------- | ------- |\n` +
    `${rows}\n`
  );
}

function renderCliVerb(cmd: Command): string {
  let out = `${BANNER}\n\n# \`clobber ${cmd.name}\`\n\n${cmd.summary}\n`;
  if (cmd.local === true) {
    out += `\n_Local command — does not require an agent token._\n`;
  }
  if (cmd.subcommands !== undefined && cmd.subcommands.length > 0) {
    out += `\n## Subcommands\n\n| Subcommand | Capability |\n| ---------- | ---------- |\n`;
    for (const sub of cmd.subcommands) {
      out += `| \`${sub.name}\` | ${sub.capability ?? "—"} |\n`;
    }
  }
  return out;
}

function renderPermissions(capabilities: readonly CliCapability[]): string {
  const tags = ["read", "write", "admin"] as const;
  const byTag = new Map<string, CliCapability[]>();
  for (const tag of tags) byTag.set(tag, []);
  for (const cap of capabilities) byTag.get(cap.tag)!.push(cap);

  const sections = tags.map((tag) => {
    const label = tag[0]!.toUpperCase() + tag.slice(1);
    const rows = byTag
      .get(tag)!
      .map((c) => `| \`${c.name}\` | ${c.description} |`)
      .join("\n");
    return `## ${label}\n\n| Capability | Description |\n| ---------- | ----------- |\n${rows}`;
  });

  return (
    `${BANNER}\n\n` +
    `# Permissions\n\n` +
    `Capabilities grouped by access level. Internal capabilities are not listed.\n\n` +
    `${sections.join("\n\n")}\n`
  );
}

function renderRoles(): string {
  const sections: string[] = [];

  sections.push(
    `## base\n\n` +
      `Abstract universal layer. Never spawned directly — forks (manager, worker) inherit from it.\n\n` +
      `- Permission mode: ${baseRole.permissionMode ?? "unset"}\n` +
      `- Allowed tools: ${baseRole.allowedTools.join(", ")}\n`,
  );

  for (const role of [managerRole, workerRole]) {
    const m = role.manifest;
    sections.push(
      `## ${m.name}\n\n` +
        `${m.description}\n\n` +
        `- Persistent: ${m.persistent}\n` +
        `- Default ceiling: ${m.defaultCeiling}\n` +
        `- Effort: ${m.effort ?? "unset"}\n` +
        `- Allowed CLI commands: ${m.allowedCliCommands.join(", ")}\n` +
        `- Allowed tools: ${role.allowedTools.join(", ")}\n`,
    );
  }

  return `${BANNER}\n\n# Roles\n\n${sections.join("\n")}\n`;
}

function buildChangelog(): readonly string[] {
  const paths = CHANGELOG_SOURCES.join(" ");
  try {
    const out = execSync(`git -C "${REPO_ROOT}" log --format="%H %as %s" -- ${paths}`, {
      encoding: "utf8",
      stdio: ["pipe", "pipe", "pipe"],
    });
    return out.trim().split("\n").filter(Boolean);
  } catch {
    return [];
  }
}

function renderChangelog(entries: readonly string[]): string {
  const items =
    entries.length > 0 ? entries.map((line) => `- ${line}`).join("\n") : "_No entries yet._";
  return (
    `${BANNER}\n\n` +
    `# Changelog\n\n` +
    `_Generated from git history of source metadata files._\n\n` +
    `${items}\n`
  );
}

if (import.meta.main) {
  const docsDir = join(REPO_ROOT, "docs");
  await generateDocs(docsDir);
  console.log(`Generated docs/ at ${docsDir}`);
}
